import Head from 'next/head'
import { motion as m } from 'framer-motion'

export default function Layout({ children, home }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        className={`absolute top-0 w-full h-screen px-8 grid grid-rows-2 lg:px-16 ${
          home ? 'bg-orange-100' : 'bg-red-400'
        }`}
        initial={{ y: '100%' }}
        animate={{ y: 0 }}
        exit={{ opacity: 1 }}
        transition={{ duration: 0.65, ease: 'easeOut' }}
      >
        {children}
      </m.main>
    </>
  )
}
